//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEducation
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Degree { get; set; }
        public string Institution { get; set; }
        public string Year { get; set; }
    }
}
