//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int ApplicationId { get; set; }
        public int JobId { get; set; }
        public int CandidateId { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public string Status { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Job Job { get; set; }
    }
}
