//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinderApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JobFinderDBEntities : DbContext
    {
        public JobFinderDBEntities()
            : base("name=JobFinderDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Recruiter> Recruiters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<CandidateEducation> CandidateEducations { get; set; }
        public virtual DbSet<CandidateExperience> CandidateExperiences { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
        public virtual DbSet<SavedJob> SavedJobs { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ResumeAnalysi> ResumeAnalysis { get; set; }
        public virtual DbSet<ResumeEducation> ResumeEducations { get; set; }
        public virtual DbSet<ResumeExperience> ResumeExperiences { get; set; }
        public virtual DbSet<ResumeProject> ResumeProjects { get; set; }
        public virtual DbSet<ResumeSkill> ResumeSkills { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
    
        public virtual int sp_InsertContact(string name, string email, string subject, string message)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("Subject", subject) :
                new ObjectParameter("Subject", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertContact", nameParameter, emailParameter, subjectParameter, messageParameter);
        }
    }
}
