//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeExperience
    {
        public int ExperienceId { get; set; }
        public Nullable<int> ResumeId { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public string Description { get; set; }
    
        public virtual Resume Resume { get; set; }
    }
}
